name = "LowDiscrepancySampling"
uuid = "ac268149-dad5-40e5-8d89-b78112a2c2f5"
authors = ["Shuhei Ohno", "Martin Mikkelsen"]
version = "0.0.1"

[deps]
CairoMakie = "13f3f980-e62b-5c42-98c6-ff1f3baf88f0"
Sobol = "ed01d8cd-4d21-5b2a-85b4-cc3bdc58bad4"

[compat]
CairoMakie = "0.14.0"
Sobol = "1.5.0"
julia = "1.11"
